### ISSUE TITLE
Why use Promise?

### ISSUE THREAD

**Issue by yfain** [afrad/angular2-websocket#1]
Thank you for providing this WebSocket wrapper for A2!

Why do you return a Promise from send() though?  Since you already return something, it might as well be an Observable just to be consistent with the Angular 2 approach.

When in A2 speak A2 :)

**Comment by afrad** [comment]
ng2 speaks also Promise :) I don't see any issue there. 
For a pure reactive approach it may be better to use RxJS/src/add/observable/dom/webSocket.ts

**Comment by yfain** [comment]
I know :) 

Yesterday I wrote a simple observable wrapper for WebSocket to explain how to do this in our Angular 2 book. But for the book sample application we'll use yours.

**Comment by afrad** [comment]
Ok :)
