### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mhadaily** [afrad/angular2-websocket#101]
Hi, 

it seems the repo has gotten a couple of new commits but actually there is no new release. Could you please release a new version. I am actually looking for Close() method change and that would be nice to have a newer version. 

Thanks,

**Comment by afrad** [comment]
done

**Comment by mhadaily** [comment]
wow, thanks for the swift reply, @afrad but I think there is a little issue for the version on your release "9.5.6", I assume it should be "0.9.5" or something right?

**Comment by afrad** [comment]
0.9.5 is old though it was not released. Let use a new one.

**Comment by mhadaily** [comment]
Awesome, thanks. I had a little confusion on this tab https://github.com/afrad/angular2-websocket/releases since it shows "9.5.6" as your current tag. 

Anyway awesome work. thanks
