### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by nccchirag** [afrad/angular2-websocket#11]
I'm getting the below error with the latest angular 2 & ionic beta libraries ...

node_modules\angular2-websocket\angular2-websocket.ts:1
import {Injectable} from "angular2/core";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

Kindly guide

**Comment by faisal-iqbal** [comment]
I am Having the same issue

**Comment by raphxyz** [comment]
Resolved?

**Comment by nccchirag** [comment]
Try using the module as a component post installing via npm
that works for me!

Thank You
Best Regards,
Chirag A.

**Comment by afrad** [comment]
Did you compiled the code? 
npm run compile

**Comment by nccchirag** [comment]
nope

Thank You
Best Regards,
Chirag A.

**Comment by hiraash** [comment]
#16 The fix is to simply move the ts file. Both the ts and .d.ts, being in the same folder causes the problem. The PR has the fix along with some further fixes on type mismatches.
