### ISSUE TITLE
Update Package for Angular 2 rc.1 ?

### ISSUE THREAD

**Issue by cyberbobjr** [afrad/angular2-websocket#17]
Hi, 
thanks for your job, please it's possible to update the package for angular 2 rc.1 ?

Best regards
Cyb

**Comment by jmparra** [comment]
is up to date https://github.com/afrad/angular2-websocket/blob/master/package.json#L14-16

**Comment by cyberbobjr** [comment]
Not really because angular2-websocket.ts still referencing old library from "angular2" and not "@angular"

**Comment by cyberbobjr** [comment]
ok ^^ i'm talking about the npm package sorry :/

**Comment by ywmail** [comment]
could you please update the package to angular 2 rc.2 and publish it to the npm package?@jmparra

**Comment by afrad** [comment]
Ok will be done

**Comment by afrad** [comment]
updated
