### ISSUE TITLE
Version 0.6.3

### ISSUE THREAD

**Issue by kgiroux** [afrad/angular2-websocket#18]
Hi, 

Is angular2-websocket avalaible with Angular2 RC 1 with npm ? 

When i try to install 0.6.3 version (that should be compatible with Angular2 RC 1) , NPM try to install 0.6.2.

Did i do something wrong ?

Sincerely,

**Comment by cyberbobjr** [comment]
I have the same problem here

**Comment by Avien** [comment]
Same here, 
looks like code is updated but not published to npm

just install it via git+http to latest commit and it should work

**Comment by Gaiidenn** [comment]
Thank you for this usefull command!

@afrad Could you please publish your last release on npm?

Thanks for your great work!

**Comment by afrad** [comment]
Done. Published the last release on npm.

**Comment by Gaiidenn** [comment]
Thank you very much ;-)
