### ISSUE TITLE
#onMessageHandler(). fixed internal implementation

### ISSUE THREAD

**Issue by egatrop** [afrad/angular2-websocket#2]
I've wrapped message object into the array, because callback function had been called without any arguments and there was no access to 'arguments' array of callback.
<code>
onMessageHandler(message: MessageEvent) { 
        var pattern;
        var self = this;
        var currentCallback;
        for (var i = 0; i < self.onMessageCallbacks.length; i++) {
            currentCallback = self.onMessageCallbacks[i];
            currentCallback.fn.apply(self, [message]);
        }
    };
</code>

**Comment by afrad** [comment]
Hi, 
could you please create pull request?

**Comment by afrad** [comment]
merged
