### ISSUE TITLE
Push updates to use rc.4 and core-js to npm

### ISSUE THREAD

**Issue by bomberblue07** [afrad/angular2-websocket#26]
Please and thank you!

**Comment by afrad** [comment]
Could you please create a pull request?

**Comment by bomberblue07** [comment]
Someone else has an open pull request for the core-js migration, and it already looks like you've updated your code to be compliant with rc.4. However, these changes have not been pushed up to npm.

**Comment by bomberblue07** [comment]
Any progress on this?

**Comment by bomberblue07** [comment]
Added a pull request for core-js updates, but you still need to push it to npm after the merge

**Comment by afrad** [comment]
merged
