### ISSUE TITLE
compatible with Angular2 RC-5?

### ISSUE THREAD

**Issue by bkdotcom** [afrad/angular2-websocket#34]
I've just updated angular2 from RC-3 to RC-5 and I can't get past this error in my console

	Error: @http://localhost:3000/node_modules/angular2-websocket/angular2-websocket.js:12:5
		@http://localhost:3000/node_modules/angular2-websocket/angular2-websocket.js:1:2
		Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:323:20
		Zone</Zone</Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:216:25
		scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:571:53
		Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:356:24
		Zone</Zone</Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:256:29
		drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:474:26
		ZoneTask/this.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:426:22
		
		Evaluating http://localhost:3000/node_modules/angular2-websocket/angular2-websocket.js
		Error loading http://localhost:3000/node_modules/angular2-websocket/angular2-websocket.js as "angular2-websocket/angular2-websocket" from http://localhost:3000

It seems to be triggered by this line in angular2-websocket.js:

`var core_1 = require('@angular/core');`

systemJS config issue, or other?

I also see that angular2-websocket has this dependency:  `"@angular/core": "2.0.0-rc.4"`...  not sure if that could be a contributing factor..

**Comment by bomberblue07** [comment]
@afrad : Thoughts? I need to know if upgrading my app from RC 4 to RC 5 will break my websocket code.

**Comment by afrad** [comment]
yes it will. Will need more time for the upgrade.

**Comment by bomberblue07** [comment]
No problem. Good to know you're working on it

**Comment by Flood** [comment]
Do you have an estimation when it's compatible with RC5/RC6?

**Comment by afrad** [comment]
It should be now compatible with rc6. Please try

**Comment by Flood** [comment]
It does not work for me. The Observable.create method in send() is not executing self.fireQueue().

If I change to return Promise it works.

**Comment by bomberblue07** [comment]
@Flood : with PR #38 , is your issue fixed?

**Comment by bkdotcom** [comment]
Upgraded to RC6...   get past all the all the compile step...   app tries to load in browser... still dies when loading angular2-websocket    same spot, but with a less verbose error:

`(index):82 Error: ReferenceError: require is not defined(…)`

**Comment by jerkly** [comment]
@bkdotcom, #37
At this time you can get fix from source or wait for publishing of a new version.

**Comment by bomberblue07** [comment]
@afrad can you please push up a new version to npm?

**Comment by afrad** [comment]
Done
