### ISSUE TITLE
use stable dependencies

### ISSUE THREAD

**Issue by joost-de-vries** [afrad/angular2-websocket#4]
Tx for this component. We're starting to use it.

Unfortunately at this version it made our build unstable. The dependency in packag.json on "angular2": "^2.0.0-beta.0" made our application upgrade without any change on our side to angular-beta.05 which broke our build.

Please depend on fixed versions in releases. :smile:

**Comment by afrad** [comment]
Hi Joost, 
could you please create a pull request?

**Comment by roelleor** [comment]
@joost-de-vries does that still happen when you include a fixed dependency yourself?
