### ISSUE TITLE
Bootstrapping question and first message issue...

### ISSUE THREAD

**Issue by donjae** [afrad/angular2-websocket#46]
Hi, 2 part question: 

What would be the best way to initialize the websocket service on initialization of the app? Like, how can you bootstrap the service with angular 2.1.0 in the app module?

Other question is...
Everything is working fine **except with capturing the first message** with `getDataStream()` method/observable. Not sure if it's related to the above question (and my backend is sending messages properly), but yeah, the first message my client app captures is always `undefined`, so the messages I capture from the datastream are one event behind. 

Ex. (mirror app example)
Client Sends => `{1, 2, 3, 4}`
client getDataStream Receives => `{undefined, 1, 2, 3}`

**Comment by donjae** [comment]
To give more detail, it appears the value within the callback/subscribe is perfectly fine. But once I attempt to save the return value to a variable outside the scope, it will have a delay/undefined error.

**Comment by bomberblue07** [comment]
Is this fixed with #49 ?

**Comment by donjae** [comment]
After further testing, I discovered there was an issue with a cursor not being closed correctly on the server side from the client, which caused this issue when the client refreshed. Thanks for the notice @bomberblue07
