### ISSUE TITLE
Strange issue when subscribing to ws.getDataStream() via seperate component

### ISSUE THREAD

**Issue by donjae** [afrad/angular2-websocket#48]
Hi,

I have this strange issue where I have a `ws.getDataStream()` close to the root component, and a subscriber attached to that service via seperate component. But it's causing this weird issue where where it'll receive multiple responses from server, even though it's sending one response. 

For example, angular2 client sends request. Server send backs a response fine, and client that recieves that response fine. But if i send another request (like, the same in this scenerio), it'll double the recieved response. Send a third one, and now there's three values that the subscriber is catching. 

So an example of this issue is, client sends 1, 2, 3. server sends 1, 2, 3. client subscriber recieves 1, 22, 333

**Comment by bomberblue07** [comment]
With the changes from #49 do you still see this issue?

**Comment by donjae** [comment]
After further testing, it turns out there was an issue with a cursor not being closed when refreshing the client. Thanks for the notice
