### ISSUE TITLE
Rxjs Subject misuse

### ISSUE THREAD

**Issue by vladvelici** [afrad/angular2-websocket#5]
First of all, thanks for writing this!

I have run into an issue and I don't know what would be a nice solution. Briefly: when a websocket connection fails, both onClose and onError are called, which makes sense, except for the `dataStream` subject.

Consider this snippet:

    var x = new Subject();
    x.error("error message");
    // x.isCompleted === true, therefore:
    x.complete(); // raises an ObjectUnsubscribedError

This is exactly what happens when an error occurs. I don't know what would be a nice solution for this, especially if you consider that you (sort of) want to abstract away reconnects in the dataStream (or at least that would be nice from my point of view).

Currently you would need to create another Subject for a new connection, and get the *clients* to resubscribe. This is OK but might need a bit of refactoring to make this obvious. Example: give the Subject as a parameter to the `onInit` callback, so it clearly represents only one connection.

Now I'm just using a stripped down version that does not have that Subject, and use only the callbacks and have my own observables that also perform some application logic.

I'm happy to make a PR after we discuss what would be a nice solution.

All the best,
Vlad

**Comment by afrad** [comment]
Hi Vlad, 
That would be a solution. In the meanwhile rxjs created its own websocket. I'm not sure if we can make use it. 
https://github.com/ReactiveX/RxJS/blob/2ef4682f7e6d2e305a1d5a81091c0f8364569024/src/observable/dom/WebSocketSubject.ts

**Comment by peter-fu** [comment]
How about perform the `this.dataStream.complete()` only when it doesn't need to reconnect?

```
    onCloseHandler(event: CloseEvent) {
       console.log('$WS.onCloseHandler()', arguments);
       console.log(event.code, this.normalCloseCode, this.reconnectableStatusCodes);
        this.notifyCloseCallbacks(event);
        if ((this.config.reconnectIfNotNormalClose && event.code !== this.normalCloseCode) || this.reconnectableStatusCodes.indexOf(event.code) > -1) {
            console.log('need reconnect');
            this.reconnect();
        } else {
          console.log('no need to reconnect')
          this.dataStream.complete();
        }
    };
```

**Comment by afrad** [comment]
Good idea. Could you please create a PR?

**Comment by peter-fu** [comment]
Cool. PR attached.
