### ISSUE TITLE
Socket connection has been closed

### ISSUE THREAD

**Issue by juniordesenv** [afrad/angular2-websocket#55]
Good Night, I am trying to send a message through the socket, but it occurs:

Socket connection has been closed

My Service:

ws = new $WebSocket("ws://localhost:1337/");

send(msg){
    this.ws.send(msg).subscribe(
        (msg)=> {
          console.log("next", msg.data);
        },
        (msg)=> {
          console.log("error", msg);
        },
        ()=> {
          console.log("complete");
        }
    );
  }

**Comment by afrad** [comment]
Hi @juniordesenv 
Please check your backend. I see no problem in your code.
