### ISSUE TITLE
Problem upgrading from 0.8.1 to 0.9.0

### ISSUE THREAD

**Issue by bomberblue07** [afrad/angular2-websocket#57]
I finally got around to upgrading my version to 0.9.0 in my project but it broke everything.

Upon first connect I get a 

> Error during WebSocket handshake: Invalid status line

According to my logs, the websocket response is a status code of 200 and not 101. If `reconnectIfNotNormalClose: true,` I see another websocket request go out (code 101), but this never gets a response back from my server, not even an error code.

Relevant code: 
`private connectWebSocket() {
        this.wsocket = new $WebSocket("wss://" + location.hostname + "/wss/whSocket");
        this.wsocket.onMessage(this.processData, {});
        this.wsocket.onError(this.socketError);
    }`

`onMessage()` is never called

**Comment by bomberblue07** [comment]
@Lyoko-Jeremie or @afrad any ideas?

**Comment by bomberblue07** [comment]
Just to be clear, my code works perfectly under 0.8.1

**Comment by afrad** [comment]
@bomberblue07 could you please provide an example we can check with?

**Comment by jerkly** [comment]
Problem introduced with this commit 908aa55f87dc312c0d97546a9f042890b8e45f78
```typescript
self.socket.onmessage = (ev: MessageEvent) => {
    // console.log('onNext: ', ev.data);
    // self.onMessageHandler(ev);
    this.dataStream.next(ev);
};
```
Commented line `self.onMessageHandler(ev);`
