### ISSUE TITLE
add angular2-websocket to typings

### ISSUE THREAD

**Issue by zamrokk** [afrad/angular2-websocket#6]
Please can you add this module to Typings ?

How can I use this module on Angular 2 if I use Typings ? I got an error "angular2-websocket not found"

Thanks

**Comment by TekSiDoT** [comment]
You don't really need Typings for this to work, it suffices to register it as a service.

**Comment by zamrokk** [comment]
I have done the injection on my service as it 

```
import {$WebSocket} from "angular2-websocket/angular2-websocket";

@Injectable()
export class DeviceService {

    private logger:Logger;
    private ws:$WebSocket;

    constructor(
        private _logger: Logger
    ) {
        this.logger=_logger;
        this.ws = new $WebSocket("ws://nodered-iot-cloud.mybluemix.net/ws/devices");
    }

    private _devices:Device[] = [];

    getDevices() {

        this.ws.send("Hello");
...
```

On my browser I get this :

GET http://localhost:1880/angular2-websocket/angular2-websocket 404 (Not Found)

**Comment by KapuzenSohn** [comment]
Your problem is not a typings problem.
The Browser cannot find the file. Are you sure that the path is right?

**Comment by bkdotcom** [comment]
I have the same user issue
I'm guessing it's a SystemJS thing

`npm install angular2-websocket`  created the angular2-websocket dir within the node_modules dir...

**Comment by fs123** [comment]
I faced the same issue. Nearly the same code and a 404 request to `http://localhost:3000/angular2-websocket/angular2-websocket`.
And I found a following workaround - I changed my System.config in `index.html` file from

        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                }
            }
        });
        System.import('app/main')
                .then(null, console.error.bind(console));

to 
        
         System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'angular2-websocket': {
                    format: 'register',
                    defaultExtension: 'js'
                }
            },
            map: {
                'angular2-websocket': 'node_modules/angular2-websocket'
            },
        });
        System.import('app/main')
                .then(null, console.error.bind(console));

And now it works

**Comment by afrad** [comment]
I see. Thanks for the help. Is there a way to fix it?

**Comment by bkdotcom** [comment]
@afrad  I think it's the documentation that needs more detail / guidance for us noobs

**Comment by afrad** [comment]
@bkdotcom  Could you please create a pull request? It would be great.
