### ISSUE TITLE
got "Socket connection has been closed" while sending data

### ISSUE THREAD

**Issue by lesliesu** [afrad/angular2-websocket#61]
when send data with default subscribe mode, I got "Socket connection has been closed" error;
but I could confirm the socket was still alive as I could still receive server side data with getDataStream() after got that error;

Also I tested with "Simple Web Socket Tool" and I haven't got issues like above.

My code:
`this.ws.send(JSON.stringify(params)).publish().connect();
    console.log('1');
    this.ws.send(JSON.stringify(params), WebSocketSendMode.Direct);

    this.ws.send(JSON.stringify(params), WebSocketSendMode.Promise).then(
      (T) => {
        console.log('is send');
      },
      (T) => {
        console.log('not send');
      }
    );

    this.ws.send(JSON.stringify(params)).subscribe(
      (msg) => {
        console.log('next', msg.data);
      },
      (msg) => {
        console.log('error', msg);
      },
      () => {
        console.log('complete');
      }
    );`

**Comment by alexjc** [comment]
I think there's a bug in `send4Direct`, this conditonal in particular:

```
if (self.socket.readyState !== self.readyStateConstants.RECONNECT_ABORTED) {
            return false;
}
```

The only cases where this succeeds and fires the queue is when `readyState === RECONNECT_ABORTED`.  It should likely `fireQueue` and return `true` if the connection is `OPEN`.  Not sure how this ever worked...

**Comment by alexjc** [comment]
Here's an ugly work-around for the problem:
```
ws.send(msg).subscribe(
      (data: any) => {},
      (error: any) => { console.log('RETRY:', error); this.ws.fireQueue(); }
    );
```

**Comment by kwalski** [comment]
Agree with alexjc, I think operator should be === instead of !== in condition
`self.socket.readyState !== self.readyStateConstants.RECONNECT_ABORTED`

**Comment by raugaral** [comment]
There is a pull request opened to solve this problem.

https://github.com/afrad/angular2-websocket/pull/65
