### ISSUE TITLE
Should getDataStream.subscribe continue to fire after re-connection?

### ISSUE THREAD

**Issue by NadavK** [afrad/angular2-websocket#78]
I create a $websocket instance with the reconnect param: `{"reconnectIfNotNormalClose": true}` and the stream nicely reconnects on failures.

I have a problem with incoming messages:
`ws.getDataStream().subscribe` correctly fires on incoming messages _until the websocket reconnects_, after which it stops firing.

Am I missing a step so `ws.getDataStream().subscribe` continues firing after an automatic reconnection?

here is the code (comments welcome, I am new to js):

    this.ws = new $WebSocket('wss://...', null, JSON.parse('{"reconnectIfNotNormalClose": true}'));
    this.ws.getDataStream().subscribe(
      (msg: MessageEvent) => console.log('message received: ', msg),
      (err) => console.log('incoming websocket err', err),
      () => console.log('incoming websocket complete')
    );

I also tried moving the `subscribe` into the stream's `onOpen`, but it behaves the same as above (fires only for the initial connection):

    this.ws = new $WebSocket('wss://...', null, JSON.parse('{"reconnectIfNotNormalClose": true}'));
    this.stream.onOpen(
      this.ws.getDataStream().subscribe(
        (msg: MessageEvent) => console.log('message received: ', msg),
        (err) => console.log('incoming websocket err', err),
        () => console.log('incoming websocket complete')
      )
    );

**Comment by NadavK** [comment]
Can anyone provide a hint?

**Comment by godzie44** [comment]
Do you finded the solution of this?

**Comment by NadavK** [comment]
No, I don't have a solution.
Maybe I am not using the package correctly - is there a working sample code?

**Comment by godzie44** [comment]
I'm fixed this problem by adding stream for error messages. You can watch my solution in fork.
