### ISSUE TITLE
Relative url

### ISSUE THREAD

**Issue by mburger81** [afrad/angular2-websocket#8]
Hi, a question, how can I set the websocket path realtive and not absolut.

ws://api/v1.... does not work

Is it possible also the set wss or ws dynamically? It depends from where I came if I came over https or http.

thx

**Comment by nextsoftpl** [comment]
it's impossible it must be absolute:
```
var filePathIndex = window.location.pathname.lastIndexOf('/') + 1;
var fileName = window.location.pathname.substr(0, filePathIndex);
var wsProtocol = window.location.protocol !== 'https:' ? 'ws' : 'wss';
var finalName = wsProtocol + '://' + window.location.host + fileName + 'ws';
```

**Comment by afrad** [comment]
You could create a settings class, 
````
export const _settings = {
 wsEndpoint: 'ws://<domain>/api/',
<othe consts>
}
````
and then refer relative to it

**Comment by nextsoftpl** [comment]
this way you have to change it for every domain you deploy the app

**Comment by roelleor** [comment]
just make your url a variable that depends on the domain which is also a (settings) variable

**Comment by mburger81** [comment]
@roelleor @nextsoftpl Did you resolved this??? Can  you share more code for this?
