### ISSUE TITLE
Can not close websocket manually

### ISSUE THREAD

**Issue by mburger81** [afrad/angular2-websocket#85]
On leaving the page, or component I try to close the WebSocket manually, doing this:
```
ngOnDestroy() {
        if (this.ws) {
            // close immediately
            this.ws.close(true);
        }
}
```
But it is not working, the WebSocket is not closed and still there, so if I enter many times in the page we have many WebSocket opened and also doubled by the #76 bug.

Does anyone experiencing the same issue or can help?

**Comment by mburger81** [comment]
I think this issue should been resolved so I can close it!

I opened a new issue for a similar issue on reconnecting attempts which could not be interrupted #87

**Comment by ugam44** [comment]
I am having this issue on v0.9.5. I have the exact same code in the ngOnDestroy() function and it is never killing the websocket connection. Any suggestions?
