### ISSUE TITLE
onOpen and onClose event not working 

### ISSUE THREAD

**Issue by mdonalisio** [afrad/angular2-websocket#9]
Hi, method onOpen and onClose not working, this is my code.

`             this.webSocket = new $WebSocket("ws://localhost:8000");

               console.log("Conectando");
		
		this.webSocket.onMessage(function(message) {
			console.log(message.data);
		}, null);

		this.webSocket.onOpen(function() {
			console.log("Open");
		});

		this.webSocket.onClose(function() {
			console.log("Cerrando");
		});		`

**Comment by afrad** [comment]
Can't really see the problem in your code. Could you please explain more.

**Comment by jmparra** [comment]
you need to connect manually
```javascript
this.webSocket.connect();
```

**Comment by duccadhv** [comment]
aaa
