### ISSUE TITLE
FR WebSocketConfig parameters should be optional

### ISSUE THREAD

**Issue by mburger81** [afrad/angular2-websocket#92]
We think WebSocketConfig parameters should be optional and merged with default values.

So for example on using default initial and maxTimeout we can only pass reconnectIfNotNormalClose and set it true and use the default paramters.
We created a PR for that #91

**Comment by afrad** [comment]
merged

**Comment by mburger81** [comment]
Thx, please update package.json and release a new version on npm thx.

**Comment by afrad** [comment]
done

**Comment by mburger81** [comment]
@afrad you have also to update the definition file

**Comment by afrad** [comment]
done

**Comment by mburger81** [comment]
still same issue .... what't do you intend with done?
there is no commit about it?
Also I think you should do the bundle in a different way, with an automatic build script. I could do a PR for that in the next week?
